In [1]:
from pyspark import SparkContext

In [2]:
sc = SparkContext(appName='2_Income_Classification')

In [3]:
numPartitions = 2
path = '/home/praneeth/Downloads/adult.data_Cfinal.csv'

In [4]:
rawData = sc.textFile(path, numPartitions)

In [5]:
rawData.take(10)

[u'0,39,77516,13,2174,0,40,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0',
 u'0,50,83311,13,0,0,13,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0',
 u'0,38,215646,9,0,0,40,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0',
 u'0,53,234721,7,0,0,40,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0',
 u'0,28,338409,13,0,0,40,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,

In [6]:
from pyspark.mllib.regression import LabeledPoint
from pyspark.mllib.linalg import Vectors, Matrices
import numpy as np

In [7]:
def parsePoint(line):
    values = [float(x) for x in line.split(',')]
    return LabeledPoint(values[0], values[1:])

In [8]:
parsedSamplePoints = rawData.map(parsePoint)

In [241]:
parsedSamplePoints.take(5)

[LabeledPoint(0.0, [39.0,77516.0,13.0,2174.0,0.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0]),
 LabeledPoint(0.0, [50.0,83311.0,13.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0]),
 LabeledPoint(0.0, [38.0,215646.0,9.0,0.0,0.0,40.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.

In [9]:
weights = [.6, .02, .02]
seed = 42
parsedTrainData, parsedValData, parsedTestData = parsedSamplePoints.randomSplit(weights,seed)
parsedTrainData.cache()
parsedValData.cache()
parsedTestData.cache()

PythonRDD[5] at RDD at PythonRDD.scala:43

In [10]:
nTrain = parsedTrainData.count()
nVal = parsedValData.count()
nTest = parsedTestData.count()

print nTrain, nVal, nTest, nTrain + nVal + nTest
print parsedSamplePoints.count()

30561 969 1031 32561
32561


In [244]:
parsedTestData.first()

LabeledPoint(0.0, [43.0,117037.0,7.0,0.0,2042.0,40.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0])

In [45]:
from pyspark.mllib.classification import SVMWithSGD, SVMModel
# Build the model

model = SVMWithSGD.train(parsedTrainData, iterations=1000,step=0.001,regParam=0.01)

In [46]:
print model.threshold

0.0


In [47]:
# Evaluating the model on training data
labelsAndPreds = parsedTrainData.map(lambda p: (p.label, float(model.predict(p.features))))
trainErr = labelsAndPreds.filter(lambda (v, p): v != p).count() / float(parsedTrainData.count())
print("Training Error = " + str(trainErr))


Training Error = 0.227806681719


In [14]:
labelsAndPreds.take(10)

[(0.0, 0.0),
 (0.0, 0.0),
 (0.0, 0.0),
 (0.0, 0.0),
 (0.0, 0.0),
 (0.0, 0.0),
 (0.0, 0.0),
 (1.0, 0.0),
 (1.0, 1.0),
 (1.0, 0.0)]

In [48]:
from pyspark.mllib.evaluation import BinaryClassificationMetrics

In [49]:
metrics = BinaryClassificationMetrics(labelsAndPreds)
AUC = metrics.areaUnderROC
APR = metrics.areaUnderPR

print("train AreaUnderCurve = " + str(AUC))
#print("train AreaUnderPrecision" +str(APR))

train AreaUnderCurve = 0.839317004042


In [50]:
# Evaluating the model on validation data
labelsAndPredsval = parsedValData.map(lambda p: (p.label, float(model.predict(p.features))))
valErr = labelsAndPreds.filter(lambda (v, p): v != p).count() / float(parsedValData.count())
print("validation Error = " + str(valErr))

# Evaluating the model on validation data
labelsAndPredstest = parsedTestData.map(lambda p: (p.label, float(model.predict(p.features))))
testErr = labelsAndPreds.filter(lambda (v, p): v != p).count() / float(parsedTestData.count())
print("Test Error = " + str(testErr))


validation Error = 7.18472652219
Test Error = 6.75266731329


In [51]:
metrics = BinaryClassificationMetrics(labelsAndPredsval)
AUC = metrics.areaUnderROC
APR = metrics.areaUnderPR

print("validation AreaUnderCurve = " + str(AUC))
#print("validation AreaUnderPrecision" +str(APR))

metrics = BinaryClassificationMetrics(labelsAndPredstest)
AUC = metrics.areaUnderROC
APR = metrics.areaUnderPR

print("test AreaUnderCurve = " + str(AUC))
#print("test AreaUnderPrecision" +str(APR))

validation AreaUnderCurve = 0.846767466111
test AreaUnderCurve = 0.878312070658


In [52]:
from sklearn.metrics import confusion_matrix

In [53]:
labelsAndPreds.take(3)

[(0.0, 0.0), (0.0, 0.0), (0.0, 0.0)]

In [54]:
import numpy as np

In [55]:
p = np.array(labelsAndPreds.collect())
confusion_matrix(p[:,0],p[:,1])

array([[23141,    46],
       [ 6916,   458]])

In [56]:
p = np.array(labelsAndPredsval.collect())
confusion_matrix(p[:,0],p[:,1])

array([[761,   1],
       [198,   9]])

In [57]:
p = np.array(labelsAndPredstest.collect())
confusion_matrix(p[:,0],p[:,1])

array([[771,   0],
       [248,  12]])

In [58]:
from pyspark.mllib.classification import LogisticRegressionWithLBFGS

In [59]:
model = LogisticRegressionWithLBFGS.train(parsedTrainData,iterations=1000,regParam=0.01)

In [60]:
model.clearThreshold

<bound method LogisticRegressionModel.clearThreshold of (weights=[0.0142509318624,2.24978144553e-07,-0.0270809882155,0.000142164465012,0.000541786462838,0.0215096224796,0.137197670849,-0.433463962045,-0.925949535162,-0.432556732088,-0.0975547652454,-0.73286058513,-0.611497342175,-2.63213036116,-1.30606537964,-1.16289252294,-0.841510571651,-1.85301856089,-1.58400619411,-1.74301528331,-1.54070546677,-0.0404973186437,-0.0458923109769,0.56806773295,1.64672987062,-0.615035058638,1.01212879401,-2.646115347,1.46732048924,-0.265668407028,-0.472679440758,1.09147927114,0.492632639275,-0.598725657021,-0.969915137113,-0.572019219608,-0.407122815891,-0.247097817598,-1.2818444637,-0.190209513874,0.481080548816,-1.03292629382,-0.837445500162,-0.524515401925,-0.947884106237,-1.39401749998,6.94826981408e-05,0.196841028393,0.0173482484742,0.293828406473,-0.347103512366,0.210734465099,-0.357141050394,-0.777840962047,-1.1201713478,-0.534785585169,1.17201184797,-1.07059709339,-0.702535325143,-0.73665073813

In [61]:
# Evaluating the model on training data
labelsAndPreds = parsedTrainData.map(lambda p: (p.label, float(model.predict(p.features))))
trainErr = labelsAndPreds.filter(lambda (v, p): v != p).count() / float(parsedTrainData.count())
print("Training Error = " + str(trainErr))

Training Error = 0.149373384379


In [62]:
metrics = BinaryClassificationMetrics(labelsAndPreds)
AUC = metrics.areaUnderROC
APR = metrics.areaUnderPR

print("train AreaUnderCurve = " + str(AUC))
#print("train AreaUnderPrecision" +str(APR))

train AreaUnderCurve = 0.809700695293


In [63]:
p = np.array(labelsAndPreds.collect())
confusion_matrix(p[:,0],p[:,1])

array([[21714,  1473],
       [ 3092,  4282]])

In [64]:
# Evaluating the model on validation data
labelsAndPredsval = parsedValData.map(lambda p: (p.label, float(model.predict(p.features))))
valErr = labelsAndPreds.filter(lambda (v, p): v != p).count() / float(parsedValData.count())
print("validation Error = " + str(valErr))

# Evaluating the model on validation data
labelsAndPredstest = parsedTestData.map(lambda p: (p.label, float(model.predict(p.features))))
testErr = labelsAndPreds.filter(lambda (v, p): v != p).count() / float(parsedTestData.count())
print("Test Error = " + str(testErr))


validation Error = 4.71104231166
Test Error = 4.4277400582


In [66]:
p = np.array(labelsAndPredsval.collect())
confusion_matrix(p[:,0],p[:,1])



array([[710,  52],
       [105, 102]])

In [67]:
p = np.array(labelsAndPredstest.collect())
confusion_matrix(p[:,0],p[:,1])

array([[711,  60],
       [111, 149]])

In [68]:
from pyspark.mllib.tree import GradientBoostedTrees, GradientBoostedTreesModel


In [69]:
model = GradientBoostedTrees.trainClassifier(parsedTrainData,
    categoricalFeaturesInfo={}, numIterations=3)

In [70]:
# Evaluate model on train instances and compute test error
predictions = model.predict(parsedTrainData.map(lambda x: x.features))
labelsAndPredictions = parsedTrainData.map(lambda lp: lp.label).zip(predictions)
testErr = labelsAndPredictions.filter(lambda (v, p): v != p).count() / float(parsedTrainData.count())
print('Test Error = ' + str(testErr))
print('Learned classification GBT model:')
print(model.toDebugString())

Test Error = 0.162756454305
Learned classification GBT model:
TreeEnsembleModel classifier with 3 trees

  Tree 0:
    If (feature 32 <= 0.0)
     If (feature 3 <= 7443.0)
      If (feature 2 <= 13.0)
       Predict: -0.9251399557349304
      Else (feature 2 > 13.0)
       Predict: -0.4783625730994152
     Else (feature 3 > 7443.0)
      If (feature 0 <= 21.0)
       Predict: -0.6
      Else (feature 0 > 21.0)
       Predict: 1.0
    Else (feature 32 > 0.0)
     If (feature 2 <= 12.0)
      If (feature 3 <= 7443.0)
       Predict: -0.37475201002401587
      Else (feature 3 > 7443.0)
       Predict: 0.9492753623188406
     Else (feature 2 > 12.0)
      If (feature 3 <= 7443.0)
       Predict: 0.3658008658008658
      Else (feature 3 > 7443.0)
       Predict: 0.9922330097087378
  Tree 1:
    If (feature 0 <= 33.0)
     If (feature 4 <= 1844.0)
      If (feature 3 <= 2597.0)
       Predict: -0.5228933422820999
      Else (feature 3 > 2597.0)
       Predict: 0.11157087847544322
     Else (

In [71]:
metrics = BinaryClassificationMetrics(labelsAndPredictions)
AUC = metrics.areaUnderROC
APR = metrics.areaUnderPR

print("train AreaUnderCurve = " + str(AUC))
#print("train AreaUnderPrecision" +str(APR))


train AreaUnderCurve = 0.802486878864


In [72]:
p = np.array(labelsAndPredictions.collect())
confusion_matrix(p[:,0],p[:,1])

array([[22006,  1181],
       [ 3793,  3581]])

In [74]:
# Evaluate model on val instances and compute test error
predictions = model.predict(parsedValData.map(lambda x: x.features))
labelsAndPredictions = parsedValData.map(lambda lp: lp.label).zip(predictions)
testErr = labelsAndPredictions.filter(lambda (v, p): v != p).count() / float(parsedTrainData.count())
print('validation Error = ' + str(testErr))
print('Learned classification GBT model:')
print(model.toDebugString())

validation Error = 0.00516998789307
Learned classification GBT model:
TreeEnsembleModel classifier with 3 trees

  Tree 0:
    If (feature 32 <= 0.0)
     If (feature 3 <= 7443.0)
      If (feature 2 <= 13.0)
       Predict: -0.9251399557349304
      Else (feature 2 > 13.0)
       Predict: -0.4783625730994152
     Else (feature 3 > 7443.0)
      If (feature 0 <= 21.0)
       Predict: -0.6
      Else (feature 0 > 21.0)
       Predict: 1.0
    Else (feature 32 > 0.0)
     If (feature 2 <= 12.0)
      If (feature 3 <= 7443.0)
       Predict: -0.37475201002401587
      Else (feature 3 > 7443.0)
       Predict: 0.9492753623188406
     Else (feature 2 > 12.0)
      If (feature 3 <= 7443.0)
       Predict: 0.3658008658008658
      Else (feature 3 > 7443.0)
       Predict: 0.9922330097087378
  Tree 1:
    If (feature 0 <= 33.0)
     If (feature 4 <= 1844.0)
      If (feature 3 <= 2597.0)
       Predict: -0.5228933422820999
      Else (feature 3 > 2597.0)
       Predict: 0.11157087847544322
   

In [76]:
# Evaluate model on val instances and compute test error
predictions = model.predict(parsedTestData.map(lambda x: x.features))
labelsAndPredictions = parsedTestData.map(lambda lp: lp.label).zip(predictions)
testErr = labelsAndPredictions.filter(lambda (v, p): v != p).count() / float(parsedTestData.count())
print('Test Error = ' + str(testErr))
print('Learned classification GBT model:')
print(model.toDebugString())

Test Error = 0.171677982541
Learned classification GBT model:
TreeEnsembleModel classifier with 3 trees

  Tree 0:
    If (feature 32 <= 0.0)
     If (feature 3 <= 7443.0)
      If (feature 2 <= 13.0)
       Predict: -0.9251399557349304
      Else (feature 2 > 13.0)
       Predict: -0.4783625730994152
     Else (feature 3 > 7443.0)
      If (feature 0 <= 21.0)
       Predict: -0.6
      Else (feature 0 > 21.0)
       Predict: 1.0
    Else (feature 32 > 0.0)
     If (feature 2 <= 12.0)
      If (feature 3 <= 7443.0)
       Predict: -0.37475201002401587
      Else (feature 3 > 7443.0)
       Predict: 0.9492753623188406
     Else (feature 2 > 12.0)
      If (feature 3 <= 7443.0)
       Predict: 0.3658008658008658
      Else (feature 3 > 7443.0)
       Predict: 0.9922330097087378
  Tree 1:
    If (feature 0 <= 33.0)
     If (feature 4 <= 1844.0)
      If (feature 3 <= 2597.0)
       Predict: -0.5228933422820999
      Else (feature 3 > 2597.0)
       Predict: 0.11157087847544322
     Else (

In [77]:
metrics = BinaryClassificationMetrics(labelsAndPredictions)
AUC = metrics.areaUnderROC
APR = metrics.areaUnderPR

print("test AreaUnderCurve = " + str(AUC))
#print("train AreaUnderPrecision" +str(APR))
p = np.array(labelsAndPredictions.collect())
confusion_matrix(p[:,0],p[:,1])

test AreaUnderCurve = 0.797235635804


array([[730,  41],
       [136, 124]])

In [78]:
sc.stop()